#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# If package.json OR package-lock.json has changed, run npm install
if git diff --name-only $1 $2 | grep -E '^(package\.json|package-lock\.json)$'; then
    # Check specifically for package.json and exclude version field changes
    if git diff -U0 $1 $2 -- package.json | grep -v '"version":' | grep -qE '^[+-][^+-]'; then
        echo "Detected changes in package.json excluding version. Running npm install…"
        npm install
    elif git diff --name-only $1 $2 | grep -qE '^package-lock\.json$'; then
        echo "Detected changes in package-lock.json. Running npm install…"
        npm install
    fi
fi

# Check if this was a branch checkout, then run branch name check
if [ "$3" -eq 1 ]; then
    sh .husky/check-branch-name.sh
fi

