name: Generate News feed

on:
  schedule:
    # Runs at 5 minutes past the hour.
    - cron: '*/2 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
#        fetch-depth: 0
      #        ref: main
        token: ${{ secrets.BOT_ACCESS_TOKEN }}
    - name: Configure git
      run: |
        git config user.name "GitHubActions"
        git config user.email "<>"
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      working-directory: ./.github/ci
      run: npm install

    - name: Generate Feed
      working-directory: ./.github/ci
      run:  node generate-news-feed.js

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: 'mack-news/feed.xml'
        commit_message: "Update feed.xml"
