name: Generate RSS feed

on:
  schedule:
    # Run 5min past every hour
    - cron: '5 * * * *'
  pull_request:
    paths:
      - '.github/ci/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      working-directory: ./.github/ci
      run: npm install

    - name: Generate Feed
      working-directory: ./.github/ci
      run:  node generate-rss-feed.js

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9.1.1
      with:
        add: 'mack-news/feed.xml'
        message: "Update feed.xml"
