name: Tests and Linting

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Set version environment variable
      run: echo "VERSION=19.0.0" >> $GITHUB_ENV
    - name: Update package.json version
      run: |
        sudo apt-get update && sudo apt-get install -y jq
        version=$(echo $VERSION)
        jq --arg version "$version" '.version = $version' package.json > package.tmp.json && mv package.tmp.json package.json
    - run: npm install
    - run: npm run lint
    - run: npm test
      env:
        CI: true
