name: Update Package Version

on:
  push:
    tags:
      - 'v*'

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          # The bot user https://github.com/hlx-macktrucks-bot is used to commit the changes. The personal access token
          # must be created from: https://github.com/settings/tokens
          # The token is then stored in the secrets of the this.
          # see https://github.com/hlxsites/vg-macktrucks-com/settings/secrets/actions
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Update package version by release tag
        uses: BellCubeDev/update-package-version-by-release-tag@v2
        with:
          keep-v: "false"
          ignore-semver-check: "true"
          encoding: "utf8"

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHubActions"
          git config user.email "<>"
          git add package.json
          git commit -m "Update package version to ${{ github.ref_name }}"
          git push
